### ISSUE TITLE
TODO Check list

### ISSUE THREAD

**Issue by Xee1** [Xee1/Faithful32-1.7.10#3]
Check list for todo folder and main folder:
- [x] Additional Buildcraft Objects
- [x] Additional Pipes
- [x] Advanced Machines (AtomicStryker's)
- [x] Advanced Power Management
- [x] Advanced Solar Panel
- [x] Alchemical Wizardry (Blood Magic)
- [x] Apple Core
- [x] Applied Energistic 2
- [x] Archimedes
- [x] Ars Magica 2
- [x] Backpack
- [x] Battlegear2
- [x] Bibliocraft
- [x] Big Reactor
- [x] Billund
- [x] Binniecore
- [x] Biomesoplenty
- [x] Bluepower
- [x] Botania
- [x] Buildcraft
- [x] Carpentersblocks
- [x] Chargepads
- [x] Chickenchunks
- [x] Chisel
- [x] CoFH
- [x] CompactSolars
- [x] Computercraft
- [x] Dartcraft
- [x] Dimdoors
- [x] Dyetrees
- [x] EE3
- [x] Emashercore
- [x] Enderio
- [x] Enderstorage
- [x] Enchanting Plus
- [x] Exaliquo
- [x] ExNihilo
- [x] ExtraBees
- [x] ExtrabiomesXL
- [x] Extracells
- [x] ExtraTiC
- [x] ExtraTrees
- [x] ExtraUtilis
- [x] Factorization
- [x] Forestry
- [x] Funky Locomotion
- [x] Galacticraft Core
- [x] Gany surface
- [x] Genetics
- [x] Geostrata
- [x] Gravigun
- [x] Gravisuite
- [x] Gregtech_addon
- [x] Hopperduct mod
- [x] Ic2
- [x] Ic2classic
- [x] Immibis(tubestaffs)
- [x] Ironchest
- [x] Jabba
- [x] Logisticspipes
- [x] Lucky
- [x] Magical crops
- [x] Magic bees
- [x] Malisisdoors
- [x] Mekanism
- [x] Metallurgy
- [x] MFFS
- [x] Microblock
- [x] Minecraft
- [x] Minefactory reloaded
- [x] Misc peripherals
- [x] Mystcraft
- [x] Natura
- [x] NEI
- [x] Netherores
- [x] NuclearControl
- [x] OpenBlocks
- [x] Openccsensor
- [x] Pluginforforestry
- [x] Portalgun
- [x] PowerConverters
- [x] Powersuits
- [x] ProjectRed
- [x] Railcraft
- [x] RandomThings
- [x] ReactorCraft
- [x] Redstone Arsenal
- [x] Rotarycraft
- [x] Simply jetpacks
- [x] Sockets (Emasher's mods)
- [x] Steamcraft
- [x] Steve's carts
- [x] Steves factory
- [x] Thaumcraft
- [x] Thermal Expansion
- [x] Thermal Foundation
- [x] Tinker
- [x] TMechworks
- [x] TTinkerer
- [x] Twilight Forest
- [x] Underground Biomes
- [x] Warpbook
- [x] Witchery
- [x] Wrcbe_addons
- [x] Wrcbe_core
- [x] Wrcbe_logic
- [x] XReliquary
- [x] Yogpstop_qp

**Comment by Adaptivity** [comment]
ExtraTiC TODO is done.

**Comment by Xee1** [comment]
Perfect, thanks for help!

**Comment by Adaptivity** [comment]
Natura TODO is done, Tinker blocks folder not checked yet.

**Comment by Xee1** [comment]
Perfect, thanks for your help!
